spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
          google:
            redirect-uri: http://localhost:8081/login/oauth2/code/google
          kakao:
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 8081
  serverAddress: localhost
  serverName: local_server

logging:
  level:
    org.springframework.security: DEBUG