spring:
  config:
    import:
      - optional:file:env/spring.env[.properties]
  profiles:
    active: dev
    group:
      dev: dev, common
      blue: blue, common, prod
      green: green, common, prod
server:
  env: blue