spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
          google:
            redirect-uri: http://localhost:8081/login/oauth2/code/google
          kakao:
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
server:
  port: 8081
  serverAddress: localhost
  serverName: local_server