spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  logging:
    level:
      org:
        hibernate:
          SQL: debug

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: ${PORT}