spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: ${NAVER_PROD_REDIRECT_URL}
          google:
            redirect-uri: ${GOOGLE_PROD_REDIRECT_URL}
          kakao:
            redirect-uri: ${KAKAO_PROD_REDIRECT_URL}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false

server:
  serverAddress: ${PROD_SERVER_HOST}
  url: ${PROD_SERVER_URL}

logging:
  level:
    org.springframework.security: ERROR
    org.hibernate.SQL: ERROR
    root: ERROR

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs
  paths-to-match:
    - /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json